Setup Prettier for shell files

diff --git a/bin/git-setup b/bin/git-setup
--- a/bin/git-setup
+++ b/bin/git-setup
@@ -11,21 +11,22 @@
 COMMIT_MESSAGE='Initial commit'
 
 if [ "$1" == "-m" ]; then
-    COMMIT_MESSAGE=$2
-    shift; shift
+	COMMIT_MESSAGE=$2
+	shift
+	shift
 fi
 
-gitdirexists(){
-    if [ -d ".git" ]; then
-        echo ".git directory already exists, aborting"
-        exit 1
-    fi
+gitdirexists() {
+	if [ -d ".git" ]; then
+		echo ".git directory already exists, aborting"
+		exit 1
+	fi
 }
 
 dir=$(test -z "$*" && echo "." || echo "$*")
 mkdir -p "$dir" \
-  && cd "$dir" \
-  && gitdirexists \
-  && git init \
-  && git add . \
-  && git commit --allow-empty -m "$COMMIT_MESSAGE"
+	&& cd "$dir" \
+	&& gitdirexists \
+	&& git init \
+	&& git add . \
+	&& git commit --allow-empty -m "$COMMIT_MESSAGE"
