Release: exit when package.json not found in a current folder.

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -40,6 +40,11 @@ if [ -z "$1" ]; then
 	exit 1
 fi
 
+if [ ! -f "package.json" ]; then
+	error "package.json not found."
+	exit 1	
+fi
+
 # Dirty repo?
 if [ "$(git status --porcelain 2>/dev/null)" ]; then
 	error "Repo is dirty."
